### ISSUE TITLE
http_error is false for guzzle

### ISSUE THREAD

**Issue by crobytech** [yabacon/paystack-php#1]
Currently http_errors is being set as false which would mean that if the request failed for any reason the user would get only an empty result but not a description of what exactly went wrong. 

I think the same thing is happening with curl as well. No error message is returned.

**Comment by ibrahimlawal** [comment]
Was intentional. This initial release includes no tests too. Want to try your hand on this and send a pull request? More than eager to merge.

**Comment by crobytech** [comment]
Just made a pull request. And yeah it would be nice to add some proper tests, would see if I can manage.

**Comment by ibrahimlawal** [comment]
Thanks! Your pull request has been merged and composer version updated.

**Comment by crobytech** [comment]
Aite, cool!

Why was it failing on Travis though ?

**Comment by ibrahimlawal** [comment]
I included [PSR2](http://www.php-fig.org/psr/psr-2/) testing for the src folder to travis. Forces me to run 

``` bash
$ ./vendor/bin/phpcbf --standard=PSR2 ./src/
```

each time I make a change to files in the src folder before committing.

**Comment by crobytech** [comment]
Oh okay. I'll go get Code sniffer then. 
Thanks

**Comment by ibrahimlawal** [comment]
It's included with the dev dependencies. so that command will work for you too.

**Comment by crobytech** [comment]
Thanks. Just ran it. Seen the diff.
