### ISSUE TITLE
Please Enable Cookies Error

### ISSUE THREAD

**Issue by papakay** [yabacon/paystack-php#10]
Please i'm having issue initializing new transaction with paystack.

I got this error

```
"Paystack Request failed with response: '
Please enable cookies.
```
I've previously setup paystack on several servers without any issues but on this new server i'm finding it difficult to get it to work. I've also confirmed that cookies is enable on the server.

Thank you.

**Comment by ibrahimlawal** [comment]
@papakay this may be related to the server's IP being blacklisted. Please contact server admin 🤔

**Comment by papakay** [comment]
Thanks
