### ISSUE TITLE
Paystack is not redirecting my function

### ISSUE THREAD

**Issue by alcantara64** [yabacon/paystack-php#11]
after successful payment  ...it does does not insert into database
![callback](https://user-images.githubusercontent.com/33314212/35101528-93dbd544-fc68-11e7-941d-b47ccb33e6b1.PNG)
![callback2](https://user-images.githubusercontent.com/33314212/35101529-942a88f6-fc68-11e7-867f-1783092a2d10.PNG)
![callback3](https://user-images.githubusercontent.com/33314212/35101530-946bb6aa-fc68-11e7-8ffe-67323d82f019.PNG)

**Comment by ezra-obiwale** [comment]
## JS

Try
```js
{
    // ...
    callback: function() {
        console.log('callback reached');
        // ...
    }
    // ...
}
```

... and see if the console logs correctly after payment.

- If it does, then the problem isn't with the callback function. Progress to check your PHP.
- If it doesn't, the problem still isn't with this library as this is for PHP.

## PHP

- Add `die($request)` before the `if ($request) {` line.
- Check the response on the browser if it returns the expected response.
- If it does, then the problem isn't with this library or Paystack at all but your line of code after the if construct.
- If it doesn't, show the response here, then we try to resolve that.

**Comment by alcantara64** [comment]
Thanks for response can you write a js code that sends variable to a php page?

**Comment by ezra-obiwale** [comment]
I'm sorry, I can't at the moment.

**Comment by ibrahimlawal** [comment]
Your issue seems to be with Javascript rather than this library. Please consult jQuery's documentation for help on posting data to the server. Testing in [Postman (https://www.getpostman.com)](https://www.getpostman.com) before coding in browser can also help.
