### ISSUE TITLE
improvement to autoload.php

### ISSUE THREAD

**Issue by dedayoa** [yabacon/paystack-php#12]
# Problem/Motivation
Trying to get paystack-php to work with a PHP 5.3 framework...because I have no choice, really. So while running autoload.php, I get **Parse error: syntax error, unexpected '[', expecting ')'...**

## Proposed resolution
The problem is on L11. str_replace expects either a string or an array as per http://php.net/manual/en/function.str-replace.php. Switching it out with `$file .= str_replace(array('Yabacon\\', '\\'), array('', DIRECTORY_SEPARATOR), $class_name) . '.php';` seems to fix my problem. My wild guess is that this modification shouldn't break anything for newer versions of PHP.

Is that a list in PHP?

## Repeatable
Always

This is not really a bug, say a tinny winny improvement.

**Comment by dedayoa** [comment]
Turns out this is not tinny winny rara...I'll just use the APIs

**Comment by ibrahimlawal** [comment]
@dedayoa Sorry bro. I feel your pain about the PHP version. Just insist you need an update. Coding against a deprecated PHP version is unrecommended for security reasons. http://php.net/supported-versions.php

**Comment by ibrahimlawal** [comment]
At the very worst, use 5.6 (which is also close to End of life actually). https://secure.php.net/eol.php .

**Comment by dedayoa** [comment]
Thanks @Ibrahim,

Things eventually worked out with 5.4. The project is based on 
codeigniter2, so anything higher failed to work - first because of 
mysql_connect etc.

Thanks!
