### ISSUE TITLE
Verification fails for test keys

### ISSUE THREAD

**Issue by idoqo** [yabacon/paystack-php#18]
I keep getting an ``` InvalidArgumentException: A Valid Paystack Secret Key must start with 'sk_'.``` which seems to be happening because Paystack's test keys begin with 'pk' instead.

Maybe we could update the checker code in the Paystack() constructor or find a better way to check for valid keys.

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Generate a test key from paystack dashboard.
2. Attempt to pass test key as a parameter to the constructor.

**Comment by ezra-obiwale** [comment]
I know this has been closed but since no reason was given for those who may stumble on this in future, here:

> Paystack has public and secret test keys. The public key begins with **pk_** while the secret key begins with **sk_**.
> Use the appropriate key and all will be will, be it in test mode or live.

![9024d6d8-1db6-4594-b01b-3ec1325ca17b](https://user-images.githubusercontent.com/2762623/42015461-6579ae6e-7a9f-11e8-8903-b735968278c6.png)

**Comment by jgodstime** [comment]
`composer dumpautoload -o`

then clear Laravel config cache

It worked for me
