### ISSUE TITLE
Fatal error: Uncaught exception 'Yabacon\Paystack\Exception\ApiException' with message 

### ISSUE THREAD

**Issue by toonex** [yabacon/paystack-php#21]
This error shows when I submit the pay request...

Fatal error: Uncaught exception 'Yabacon\Paystack\Exception\ApiException' with message 'Paystack Request failed with response: '<html> <head><title>400 Bad Request</title></head> <body bgcolor="white"> <center><h1>400 Bad Request</h1></center> <hr><center>cloudflare</center> </body> </html> '' in C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Http\Response.php:31 Stack trace: #0 C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Http\Response.php(71): Yabacon\Paystack\Http\Response->parsePaystackResponse() #1 C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Helpers\Caller.php(20): Yabacon\Paystack\Http\Response->wrapUp() #2 C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Helpers\Router.php(84): Yabacon\Paystack\Helpers\Caller->callEndpoint(Array, Array, Array) #3 [internal function]: Yabacon\Paystack\Helpers\Router->Yabacon\Paystack\Helpers\{closure}(Array) #4 C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Helpers\Router.php(39): call_user_func_array(Object(Closure), in C:\xampp\htdocs\domain\paystack-php-master\src\Paystack\Http\Response.php on line 31

**Comment by ezra-obiwale** [comment]
Check the payload you're sending with the request. Something is not quite right there.

**Comment by ibrahimlawal** [comment]
See if this article helps: https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)

You posted an issue that has already been discussed. This is a duplicate of #7
