### ISSUE TITLE
Fatal Error Uncaught InvalidArgumentException: Class &quot;transaction&quot; does not exist. in /storage/ssd4/502/13888502/public_html/vendor/yabacon/paystack-php/src/Paystack/Helpers/Router.php:69

### ISSUE THREAD

**Issue by markomeje** [yabacon/paystack-php#30]
# Problem/Motivation
I'm getting this error on live server when trying to call the api for redirect user to payment page
0 /storage/ssd4/502/13888502/public_html/vendor/yabacon/paystack-php/src/Paystack.php(106): Yabacon\Paystack\Helpers\Router-&gt;__construct('transaction', Object(Yabacon\Paystack))
1 /storage/ssd4/502/13888502/public_html/framework/Models/Subscriptions.php(61): Yabacon\Paystack-&gt;__get('transaction')

**Comment by awijeet** [comment]
I am also getting the **same** error message

**Comment by sheanWinston** [comment]
Any work around, am having the same issue here

**Comment by sheanWinston** [comment]
For my case, I used the 2.1.23 and the error disappeareed

**Comment by awijeet** [comment]
I fixed the issue by not using the latest version. 

https://github.com/yabacon/paystack-php/releases

So instead of using "Version 2.2" I preferred "Version 2.1.22"  and I could get it working
